- hosts: all_servers
  vars_files:
    - ansible-vars/main.yml
  roles:
    - role: system
      tags: system
    - role: podman
      tags: podman
    - role: traefik
      tags: traefik
    - role: homepage
      tags: homepage
    - role: webapps
      tags: webapps
    - role: nfs
      tags: nfs
