- name: Homepage configurations
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ homelab_data_dir }}/homepage/config/{{ item }}"
  loop:
    - "services.yaml"
    - "docker.yaml"
    - "settings.yaml"
  tags: homepage_config
