- name: Homepage configurations
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ homelab_data_dir }}/homepage/config/{{ item }}"
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: '0644'
  loop:
    - "services.yaml"
    - "docker.yaml"
    - "settings.yaml"
  tags: homepage_config
