- name: Homepage services configuration
  ansible.builtin.template:
    src: "services.yaml.j2"
    dest: "{{ homelab_data_dir }}/homepage/config/services.yaml"
  become: true

- name: Homepage other configurations
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ homelab_data_dir }}/homepage/config/{{ item }}"
  loop:
    - "docker.yaml"
    - "settings.yaml"
    - "bookmarks.yaml"
  become: true

- name: Homepage background image
  ansible.builtin.copy:
    src: "homepage_bg.png"
    dest: "{{ homelab_data_dir }}/homepage/images/homepage_bg.png"
  become: true
