---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

showStats: true

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
