- name: Deploy ansible-on-start systemd unit
  become: true
  ansible.builtin.template:
    src: ansible-on-start.service.j2
    dest: /etc/systemd/system/ansible-on-start.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd to pick up new unit
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start ansible-on-start service
  become: true
  ansible.builtin.systemd:
    name: ansible-on-start.service
    enabled: true
    state: started
