- name: Ensure Traefik base directory exists
  ansible.builtin.file:
    path: "{{ homelab_data_dir }}/traefik"
    state: directory
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: '0755'

- name: Sync traefik configuration from repo
  ansible.builtin.copy:
    src: "traefik.yml"
    dest: "{{ homelab_data_dir }}/traefik/traefik.yml"
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: '0644'
